services:
  app:
    container_name: app-deps
    build:
      context: .
      dockerfile: Dockerfile
      target: deps
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

# uruchomienie, --build po to żeby pomijać kesz
# docker compose -f docker-compose-deps.yml up --build

# pokaże jaki plik zostanie wykonany
# docker compose -f docker-compose-deps.yml config
